const projects = [
  {
    id: 1,
    title: 'Assessment Okupasi API',
    description: 'A RESTful API to assess the suitability of vocational school graduate competencies with industry',
    tech: ['TypeScript', 'Node.js', 'Express.js', 'Prisma ORM', 'PostgreSQL'],
    code: 'https://github.com/dhichii/assessment-okupasi-api',
    src: '',
  },
  {
    id: 2,
    title: 'Product gRPC Service',
    description: 'Product services with gRPC',
    tech: ['Golang', 'gRPC'],
    code: 'https://github.com/dhichii/tokped-workshop-grpc',
    src: '',
  },
  {
    id: 3,
    title: 'MyCampus API',
    description: 'A RESTful API to register for college in one portal',
    tech: ['TypeScript', 'Node.js', 'Express.js', 'Prisma ORM', 'PostgreSQL'],
    code: 'https://github.com/dhichii/mycampus-api',
    src: '',
  },
  {
    id: 4,
    title: 'Universitas Negeri Manado KPI 1 API',
    description: 'A RESTful API to manage the alumni tracer',
    tech: ['Golang', 'Echo (Go)', 'GORM (Go)', 'MySQL'],
    code: 'https://github.com/IKU-UNIMA/BE-1',
    src: '',
  },
  {
    id: 5,
    title: 'Universitas Negeri Manado KPI 2 API',
    description: 'A RESTful API to manage student activities and achievements',
    tech: ['Golang', 'Echo (Go)', 'GORM (Go)', 'MySQL', 'Google Drive API'],
    code: 'https://github.com/IKU-UNIMA/BE-2',
    src: '',
  },
  {
    id: 6,
    title: 'Universitas Negeri Manado KPI 5 API',
    description: 'A RESTful API to manage the lecturer research',
    tech: ['Golang', 'Echo (Go)', 'GORM (Go)', 'MySQL', 'Google Drive API'],
    code: 'https://github.com/IKU-UNIMA/BE-5',
    src: '',
  },
  {
    id: 7,
    title: 'Universitas Negeri Manado KPI 6 API',
    description: 'A RESTful API to manage the partner collaborations',
    tech: ['Golang', 'Echo (Go)', 'GORM (Go)', 'MySQL'],
    code: 'https://github.com/IKU-UNIMA/BE-6',
    src: '',
  },
  {
    id: 8,
    title: 'Forum API',
    description: 'A RESTful API to discuss a topic in threads using Clean Architecture',
    tech: ['JavaScript', 'Node.js', 'Hapi.js', 'PostgreSQL', 'GitHub Action'],
    code: 'https://github.com/dhichii/forum-api',
    src: '',
  },
  {
    id: 9,
    title: 'OpenMusic API',
    description: 'A RESTful API to adding and collaborating on a playlist',
    tech: ['JavaScript', 'Node.js', 'Hapi.js', 'Amazon (EC2, S3)', 'PostgreSQL', 'Redis'],
    code: 'https://github.com/dhichii/openmusic-api',
    src: '',
  },
  {
    id: 10,
    title: 'Clinic Management API',
    description: 'A RESTful API to manage doctor, nurse, queue, and prescriptions',
    tech: ['Golang', 'Echo (Go)', 'GORM (Go)', 'MySQL', 'Docker', 'Amazon EC2', 'GitHub Action', 'OpenAPI'],
    code: 'https://github.com/ALTERA-CAPSTON-41/backend',
    src: '',
  },
  {
    id: 11,
    title: 'Plant API',
    description: 'A RESTful API to manage shop and selling products',
    tech: ['Golang', 'Echo (Go)', 'GORM (Go)', 'MySQL', 'Docker', 'Amazon EC2', 'GitHub Action', 'Swagger'],
    code: 'https://github.com/dhichii/plant-api',
    src: '',
  },
  {
    id: 12,
    title: 'Shop API',
    description: 'A RESTful API to manage shop and selling products',
    tech: ['Golang', 'Fiber (Go)', 'GORM (Go)', 'MySQL'],
    code: 'https://github.com/dhichii/shop-api',
    src: '',
  },
  {
    id: 13,
    title: 'MyGram API',
    description: 'A social media RESTful API to posting and commenting on photos',
    tech: ['Golang', 'Gin (Go)', 'GORM (Go)', 'PostgreSQL'],
    code: 'https://github.com/dhichii/mygram-api',
    src: '',
  },
  {
    id: 14,
    title: 'Order API',
    description: 'A RESTful API to order items',
    tech: ['Golang', 'Gin (Go)', 'GORM (Go)', 'PostgreSQL'],
    code: 'https://github.com/dhichii/order-api',
    src: '',
  },
  {
    id: 15,
    title: 'Self-Payroll API',
    description: 'A RESTful API that allow employees to do salary withdrawals independently every month',
    tech: ['Golang', 'Echo (Go)', 'GORM (Go)', 'PostgreSQL'],
    code: 'https://github.com/dhichii/order-api',
    src: '',
  },
];

const getAllProject = () => projects;

export {getAllProject}